openapi: 3.0.0

info:
  title: JobFlow Automator API
  version: 1.0.0

tags:
  - name: Auth
    description: Authentication related APIs

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token

paths:
  /auth/register:
    post:
      summary: Register a new user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, password]
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: User registered successfully

  /auth/login:
    post:
      summary: Login with email and password
      tags: [Auth]
      parameters:
        - in: header
          name: X-Client-Type
          schema:
            type: string
            enum: [mobile]
          required: false
          description: >
            Set to "mobile" for mobile clients.
            If not provided, server treats request as browser
            and sets HTTP-only cookie.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful
          headers:
            Set-Cookie:
              description: HTTP-only cookie containing JWT (browser clients only)
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
                    nullable: true
                    description: Present only for mobile clients
                  user:
                    type: object
        "401":
          description: Invalid credentials

  /auth/google:
    post:
      summary: Google signup / login
      description: >
        Authenticates user using Google ID token.
        If user does not exist, a new account is created.
        If user exists, user is logged in.
      tags: [Auth]
      parameters:
        - in: header
          name: X-Client-Type
          schema:
            type: string
            enum: [mobile]
          required: false
          description: >
            Set to "mobile" for mobile clients.
            If not provided, server treats request as browser
            and sets HTTP-only cookie.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [token]
              properties:
                token:
                  type: string
                  description: Google ID token obtained from Google Sign-In
      responses:
        "200":
          description: Google authentication successful
          headers:
            Set-Cookie:
              description: HTTP-only cookie containing JWT (browser clients only)
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
                    nullable: true
                  user:
                    type: object
        "401":
          description: Google authentication failed

  /auth/github:
    post:
      summary: GitHub authentication
      tags: [Auth]
      responses:
        "200":
          description: GitHub auth successful

  /auth/me:
    get:
      summary: Get current logged-in user
      description: >
        Returns the currently authenticated user.

        Authentication methods:
        - Mobile: Use Authorization header (Bearer token).
          Click the "Authorize" button in Swagger UI.
        - Browser: Login first to set HTTP-only cookie (access_token).
          Cookie is sent automatically by the browser.
      tags: [Auth]
      security:
        - bearerAuth: []
        - cookieAuth: []
      responses:
        "200":
          description: Current user data
          schema:
              type: object
              required: [token]
              properties:
                token:
                  type: string
                  description: middleware
        "401":
          description: Unauthorized
